module.exports = {
  LABEL_CONFIRMPERMISSION: "确认授权",
  LABEL_PLAYMOMENT: "LABEL_PLAYMOMENT",
  LABEL_YOUTUBE: "LABEL_YOUTUBE",
  LABEL_VERIFICATIOINCODETEXT: "手机验证码登录火火兔",
  LABEL_NEWUSERTIPSTEXT: "新用户无需注册直接用验证码登录",
  LABEL_GETVERIFIEDCODE: "获取验证码",
  LABEL_CONFIRM: "确认",
  LABEL_PLACEHOLDERPHONENUMBER: "请输入手机号码",
  LABEL_PLACEHOLDERVERIFIEDCODE: "请输入验证码",

  // toast
  LABEL_EMPTYUSERINFO: "用户地址缺少",
  LABEL_EMPTYPROPERTIES: "请选择商品型号",
  LABEL_NONGENDER: "请选择宝宝性别",
  LABEL_NONNICKNAME: "请输入宝宝昵称",
  LABEL_NONBIRTHDAY: "请选择宝宝生日",
};