module.exports = {
  LABEL_CONFIRMPERMISSION: "确认授权",
  LABEL_PLAYMOMENT: "LABEL_PLAYMOMENT",
  LABEL_YOUTUBE: "LABEL_YOUTUBE",
  LABEL_VERIFICATIOINCODETEXT: "手机验证码登录火火兔",
  LABEL_NEWUSERTIPSTEXT: "新用户无需注册直接用验证码登录",
  LABEL_GETVERIFIEDCODE: "获取验证码",
  LABEL_CONFIRM: "确认",
  LABEL_PLACEHOLDERPHONENUMBER: "请输入手机号码",
  LABEL_PLACEHOLDERVERIFIEDCODE: "请输入验证码",
};